### ISSUE TITLE
TODO: Preparations for flathub

### ISSUE THREAD

**Issue by ludvigng** [ludvigng/thedarkmod#1]
This is based on the suggestions from jonri on the darkmod forums:

- [x] Include a higher res icon
- [ ] Include appstream data
- [ ] Decide on proper install location for game data (so it works with DarkRadiant editor for example)
- [ ] Investigate whether `extra-data` should be used for game data

**Comment by WMan22** [comment]
There are people out there that are eagerly anticipating this so we can play on our Steam Decks and such, so thank you.
